#!/usr/bin/env python3
"""Generate .docs_chain/contexts/herald-docs.yaml — the full-corpus Docs Chain context.

The corpus = every tracked `.md` that ALREADY has a committed `.html` sibling,
EXCLUDING submodules/, containers/, constitutable/, docs/herald/diary/,
docs/superpowers/, and docs/specs/mvp/archive/ (frozen historical specs).

For each doc this emits 4 nodes (md/html/pdf/docx) + 3 derive-from edges
(md->html, md->pdf, md->docx). Transforms are grouped PER DISTINCT DIRECTORY:
one md2html_<dirslug>/md2pdf_<dirslug>/md2docx_<dirslug> triple per directory,
each carrying the doc's real directory as the exec `args:` so the wrapper can
`cd` there and resolve the relative print.css + logo <img> identically during
sync AND verify (the G6 contract — see docs/research/docs_chain/HERALD_DOCS_CHAIN_PLAN.md §3.1).

Reproducible: re-running regenerates byte-identical yaml from `git ls-files`.
"""
import subprocess
import re
import sys
import os

EXCLUDE = re.compile(
    r'^submodules/|^containers/|^constitutable/|docs/herald/diary/|'
    r'^docs/superpowers/|docs/specs/mvp/archive/'
)

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, ".docs_chain", "contexts", "herald-docs.yaml")


def git_ls(pattern):
    return subprocess.run(
        ["git", "ls-files", pattern], cwd=ROOT,
        capture_output=True, text=True, check=True
    ).stdout.splitlines()


def tracked(path):
    r = subprocess.run(
        ["git", "ls-files", "--error-unmatch", path],
        cwd=ROOT, capture_output=True, text=True
    )
    return r.returncode == 0


def has_html_sibling(md):
    return tracked(md[:-3] + ".html")


def slug(path):
    """node id slug: replace / and . with _"""
    return re.sub(r'[/.]', '_', path)


def dirslug(d):
    """transform-group slug for a directory; repo root '.' -> 'root'"""
    if d == ".":
        return "root"
    return re.sub(r'[/.]', '_', d)


def main():
    corpus = sorted(
        md for md in git_ls("*.md")
        if not EXCLUDE.search(md) and has_html_sibling(md)
    )
    if not corpus:
        print("ERROR: empty corpus", file=sys.stderr)
        sys.exit(1)

    # For each doc, only the sibling EXTENSIONS already committed in git are
    # wired — we rebaseline existing committed artefacts, never invent a new
    # committed file. (E.g. docs/guides/CONSTITUTION_INHERITANCE has html+pdf
    # committed but no docx, so its docx leg is intentionally omitted.)
    EXTS = ("html", "pdf", "docx")
    exts_for = {md: [e for e in EXTS if tracked(md[:-3] + "." + e)] for md in corpus}

    # group docs by directory (only dirs that have at least one wired edge)
    by_dir = {}
    for md in corpus:
        d = os.path.dirname(md) or "."
        by_dir.setdefault(d, []).append(md)

    lines = []
    lines.append("context: herald-docs")
    lines.append(
        "description: FLEET — every tracked Herald .md with a committed .html sibling, "
        "md -> html/pdf/docx via per-directory exec-wrapper transforms (logo print.css "
        "preserved; verify-stable per the G6 real-dir-arg contract). "
        "Generated by scripts/docs_chain/gen_context.py — do not hand-edit."
    )

    # kind + transform-verb per extension
    KIND = {"html": "html", "pdf": "pdf", "docx": "docx"}
    VERB = {"html": "md2html", "pdf": "md2pdf", "docx": "md2docx"}

    # nodes
    lines.append("nodes:")
    for md in corpus:
        base = md[:-3]
        s = slug(base)
        lines.append(f"  {s}_md: {{ kind: markdown, path: {md} }}")
        for e in exts_for[md]:
            lines.append(f"  {s}_{e}: {{ kind: {KIND[e]}, path: {base}.{e} }}")

    # edges
    lines.append("edges:")
    for md in corpus:
        s = slug(md[:-3])
        ds = dirslug(os.path.dirname(md) or ".")
        for e in exts_for[md]:
            lines.append(
                f"  - {{ type: derive-from, from: {s}_md, to: {s}_{e}, "
                f"transform: {VERB[e]}_{ds} }}"
            )

    # transforms: per distinct directory, only the extension-legs actually used
    # by some doc in that directory (the real doc dir is the exec arg; root -> ".")
    EXEC = {
        "html": "scripts/docs_chain/md_to_html.sh",
        "pdf": "scripts/docs_chain/md_to_pdf.sh",
        "docx": "scripts/docs_chain/md_to_docx.sh",
    }
    lines.append("transforms:")
    for d in sorted(by_dir):
        ds = dirslug(d)
        used = set()
        for md in by_dir[d]:
            used.update(exts_for[md])
        for e in EXTS:
            if e in used:
                lines.append(
                    f'  {VERB[e]}_{ds}: {{ exec: "{EXEC[e]}", args: ["{d}"] }}'
                )

    content = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(content)
    n_edges = sum(len(exts_for[md]) for md in corpus)
    n_nodes = len(corpus) + n_edges  # one md node per doc + one out node per edge
    n_tf = 0
    for d in by_dir:
        used = set()
        for md in by_dir[d]:
            used.update(exts_for[md])
        n_tf += len(used)
    print(f"wrote {OUT}: {len(corpus)} docs, {len(by_dir)} dirs, "
          f"{n_nodes} nodes, {n_edges} edges, {n_tf} transforms")


if __name__ == "__main__":
    main()
